server:
  port: 8888
spring:
  profiles:
    active: demo
  mvc:
    static-path-pattern: /**

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/student?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initial-size: 5
    min-idle: 5
    max-active: 20
    # 配置获取连接等待超时的时间
    max-wait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    time-between-eviction-runs-millis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    min-evictable-idle-time-millis: 300000
    validation-query: SELECT 1 FROM DUAL
    test-while-idle: true
    test-on-borrow: false
    test-on-return: false
    # 打开PSCache，并且指定每个连接上PSCache的大小
    pool-prepared-statements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    max-pool-prepared-statement-per-connection-size: 20
    filters: stat,wall
    use-global-data-source-stat: true

  data:
    mongodb:
      database: student
      port: 27017
      host: localhost

  redis:
    host: 127.0.0.1
    port: 6379
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 0

mybatis-plus:
  # 配置扫描xml
  # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
  configuration:
    # 全局地开启或关闭配置文件中的所有映射器已经配置的任何缓存，默认为 true
    cache-enabled: false
    map-underscore-to-camel-case: true
    #如果查询结果中包含空值的列，则 MyBatis 在映射的时候，不会映射这个字段
    call-setters-on-nulls: true
    # 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      db-config:
      table-underline: true
      logic-delete-field: del_flag
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/*.xml

swagger:
  title: DEMO Swagger API
  groupName: demo
  version: 1.0.0
  termsOfServiceUrl: javascript:void(0)
  license: Apache 2.0
  description: "飘飘何所似，天地一沙鸥"
  licenseUrl: http://www.apache.org/licenses/LICENSE-2.0.html
  contactName: zengkai
  contactUrl: www.baidu.com
  basePackage: com.example.demo.controller
  contactemail: 953459378@qq.com

